@startuml diagrama6

class Clase1{
    toString()
}
class Clase2{
    String[] elementos
    mostrarElementos
}

Clase1 <|-- Clase2
Clase1 <|-- Clase3
Clase4 "1" *-- "n" Clase5: agregar


class Clase8{
    String[] elementos
    mostrarElementos
}
Clase6 <|-- Clase7
Clase6 <|-- Clase8
@enduml